package com.pojo;

// Generated 13 Jan, 2020 2:55:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * Feedback generated by hbm2java
 */
public class Feedback implements java.io.Serializable {

	private Integer feedid;
	private Patient patient;
	private String status;
	private String q1;
	private String q2;
	private String q3;
	private String q4;
	private String q5;
	private String q6;
	private String q7;
	private String q8;
	private String q9;
	private String q10;
	private String attendantname;

	public Feedback() {
	}

	public Feedback(Patient patient, String status, String q1, String q2, String q3, String q4, String q5, String q6,
			String q7, String q8, String q9, String q10, String attendantname) {
		this.patient = patient;
		this.status = status;
		this.q1 = q1;
		this.q2 = q2;
		this.q3 = q3;
		this.q4 = q4;
		this.q5 = q5;
		this.q6 = q6;
		this.q7 = q7;
		this.q8 = q8;
		this.q9 = q9;
		this.q10 = q10;
		this.attendantname = attendantname;
	}

	public Integer getFeedid() {
		return this.feedid;
	}

	public void setFeedid(Integer feedid) {
		this.feedid = feedid;
	}

	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getQ1() {
		return this.q1;
	}

	public void setQ1(String q1) {
		this.q1 = q1;
	}

	public String getQ2() {
		return this.q2;
	}

	public void setQ2(String q2) {
		this.q2 = q2;
	}

	public String getQ3() {
		return this.q3;
	}

	public void setQ3(String q3) {
		this.q3 = q3;
	}

	public String getQ4() {
		return this.q4;
	}

	public void setQ4(String q4) {
		this.q4 = q4;
	}

	public String getQ5() {
		return this.q5;
	}

	public void setQ5(String q5) {
		this.q5 = q5;
	}

	public String getQ6() {
		return this.q6;
	}

	public void setQ6(String q6) {
		this.q6 = q6;
	}

	public String getQ7() {
		return this.q7;
	}

	public void setQ7(String q7) {
		this.q7 = q7;
	}

	public String getQ8() {
		return this.q8;
	}

	public void setQ8(String q8) {
		this.q8 = q8;
	}

	public String getQ9() {
		return this.q9;
	}

	public void setQ9(String q9) {
		this.q9 = q9;
	}

	public String getQ10() {
		return this.q10;
	}

	public void setQ10(String q10) {
		this.q10 = q10;
	}

	public String getAttendantname() {
		return this.attendantname;
	}

	public void setAttendantname(String attendantname) {
		this.attendantname = attendantname;
	}

}
