package com.pojo;

// Generated 13 Jan, 2020 2:55:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * Location generated by hbm2java
 */
public class Location implements java.io.Serializable {

	private Integer locid;
	private String city;
	private String state;
	private String country;

	public Location() {
	}

	public Location(String city, String state, String country) {
		this.city = city;
		this.state = state;
		this.country = country;
	}

	public Integer getLocid() {
		return this.locid;
	}

	public void setLocid(Integer locid) {
		this.locid = locid;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
